### ISSUE TITLE
Update Calsimetaw data for monthly maps

### ISSUE THREAD

**Issue by qjhart** [ssj-delta-cu/ssj-calsimetaw#2]
DWR has provided their daily summary of data by DAU -county.  In order to compare to our other estimates, we need to convert those to maps based on the land-cover estimates.  The idea is pretty simple.  For each pixel, we select the landcover type, and then from that we select the appropriate ET esimate based on what DAU-Co the data is in.

In earth engine, there are a few ways to do this:
- One way we could do this is to create a 20 band image, that includes 12 value array for each of the months for each of crop types, and then  create an expression that selects the appropriate array value based on the landcover type.
- Alternatively, we could create 12  24 band images, one for each month, and then map each of these, and the collect the final values. 

Both of these methods probably require that we create some rasters outside of earth engine.

We could also do this in postgis.

**Comment by qjhart** [comment]
@andybell the CalSIMETAW data, provided in this project (model_output directory), need to be converted to the standard monthly ET product required for this project.  @josue-medellin has assigned you to this task.  Please see the ssj-overview project for information on the format of the ET product.  

Basically, we need to take the 24 landcover product (see the ssj-landuse project).  And then add the appropriate CalSIMETAW data.  The CalSIMETAW needs to be summarized by month.  IF you look at the Makfile in this project, you can get info on where to get the DAU and county boundaries.

**Comment by andybell** [comment]
@qjhart a few things to clarify before I start working on this. 
1. It looks like the CalSIMETAW data has been aggregated by month already (starting at column X). Is this appropriate to use this data for ETc? 
2. Can you explain what the "20 band" refers to? Is each crop a separate band? Looking at the model output it looks like there is more than 20 crops for certain DAU-CO.

**Comment by qjhart** [comment]
I think that column is just the month, but yes, you could use that for the aggregation, eg.

20 was just a guess.  I've updated that to be the 24 categories.  These are joined to the landuse level_1 crop types.  You can see the names don't quite match but the crosswalk is easy.

``` sql
select distinct commodity,level_1,coalesce(commodity,level_1) from model_output full outer join landuse on (UPPER(commodity)=UPPER(level_1)) order by 3;
```

| commodity | level_1 | coalesce |
| --- | --- | --- |
| Alfalfa |  | Alfalfa |
| Almonds |  | Almonds |
| Bushberries |  | Bushberries |
| Cherries |  | Cherries |
| CitrusSubtrop |  | CitrusSubtrop |
|  | Citrus/Subtropical | Citrus/Subtropical |
| Corn |  | Corn |
| Cucurbits |  | Cucurbits |
|  | Field Crops | Field Crops |
|  | Idle | Idle |
|  | Native | Native |
|  | Native Riparian | Native Riparian |
| Olives |  | Olives |
| OtherDeciduous |  | OtherDeciduous |
|  | Other Deciduous | Other Deciduous |
| Pasture | Pasture | Pasture |
| Pears |  | Pears |
| Pistachio |  | Pistachio |
| Potatoes |  | Potatoes |
| Rice | Rice | Rice |
| Riparian |  | Riparian |
| Safflower |  | Safflower |
|  | Semi-agricultural | Semi-agricultural |
| Sunflower |  | Sunflower |
| Tomato |  | Tomato |
| TruckCrops |  | TruckCrops |
|  | Truck Crops | Truck Crops |
| Turffarm |  | Turffarm |
|  | Urban | Urban |
| UrbanLandscape |  | UrbanLandscape |
| Vineyard |  | Vineyard |
|  | Vineyards | Vineyards |
| Walnuts |  | Walnuts |
|  | Water | Water |
| WaterSurface |  | WaterSurface |

**Comment by qjhart** [comment]
@andybell , I'm going to complete this step within postgis.  Let me know if ou are quite far along, and that's not a good idea.
